#!/usr/bin/env bash

cd "$(dirname "$0")/.."

rm -rf .xo
./node_modules/.bin/ts-node-dev \
  --pretty \
  --log-error \
  --no-notify \
  --respawn \
  --watch \
  "./example_programs" \
  ./src/index.ts \
  "$@"
